artifacts:
  ARTIFACTS_DIR: artifacts
  LOG_DIR: logs
  RAW_DATA: raw_data/1-s2.0-S2352340917300628-mmc2.docx
  INITIAL_PREPARED_DATA: initial_prepared_data
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_OUT_TRAIN: train.pkl
  FEATURIZED_OUT_TEST: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl